version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis
        command: >
            sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
                   chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
                   php-fpm"
    db:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: mypassword
            MYSQL_DATABASE: oa_laravel_training_one
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
        depends_on:
            - app

volumes:
    db_data:
